# Generated by Django 2.2.dev20181125194326 on 2019-01-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='loja.Product')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='loja.UserProfile')),
            ],
        ),
    ]
