# Generated by Django 2.2.dev20181125194326 on 2019-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20190113_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='opportunity',
            field=models.BooleanField(default=False),
        ),
    ]
