# Generated by Django 2.1.3 on 2019-01-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_auto_20190123_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product',
            field=models.ManyToManyField(blank=True, to='loja.Product'),
        ),
    ]
